#.scrutinizer.yml
tools:
    external_code_coverage: true
        timeout: 1200    # Timeout in seconds.
    php_mess_detector: true
    php_code_sniffer: true
    php_code_coverage: true
    php_sim: true
    php_analyzer: true
    php_pdepend: true