# .scrutinizer.yml
tools:
    external_code_coverage:
        timeout: 1200    # Timeout in seconds.
        runs: 2    # Scrutinizer will wait for two code coverage submissions
    php_mess_detector: true
    php_code_sniffer: true
    php_code_coverage: true
    php_sim: true
    php_analyzer: true
    php_pdepend: true